### ISSUE TITLE
place the switch in the middle of the screen

### ISSUE THREAD

**Issue by richardmsk** [richardmsk/click#1]
Currently the switch on and switch off pngs are under one and another, I want them to appear in the same place in the middle of the screen. 

this is the design I am trying to achieve (with my new switch image) 

![sx_画板 1 副本 4](https://user-images.githubusercontent.com/91919871/137226812-048cef3a-41f6-44d9-8e01-38c3d17e7860.jpg)

**Comment by sehsarah** [comment]
Closing as this one has been addressed
