### ISSUE TITLE
page layout 

### ISSUE THREAD

**Issue by richardmsk** [richardmsk/click#2]
Images duplicate in the following order, red bottom; switch; bulb; each with sound effects linked to interactions, finishing each page plays a short cut of music then changes into black then into the next subject.

**Comment by richardmsk** [comment]
![light-on](https://user-images.githubusercontent.com/91919871/137835704-69654f95-e932-4e0f-9089-866724239184.png)
![switch-off](https://user-images.githubusercontent.com/91919871/137835707-f20f3a92-0344-479d-90d1-ed09278db387.png)
![switch-on](https://user-images.githubusercontent.com/91919871/137835709-55c87232-4332-4833-a10c-4b3f4266a45a.gif)
![botton-off](https://user-images.githubusercontent.com/91919871/137835710-98df17c0-b26c-40c5-a726-a1e7189cfc64.png)
![botton-on](https://user-images.githubusercontent.com/91919871/137835712-2ac4a9a6-9ab2-4264-b59d-6ee7e074a3ff.gif)
![light-off](https://user-images.githubusercontent.com/91919871/137835713-b97436da-b9f7-45a9-bfcb-850f5adf4f6e.gif)

**Comment by sehsarah** [comment]
You can close this one as it's addressed now yeah @richardmsk ?
